import sys
p = 'scripts/reporting/html_template.py'
with open(p, 'r', encoding='utf-8') as f: t = f.read()

old1 = "    # Build chart series from peak_rows (Chart.js needs labels+data)\n    chart_labels = [r[0] for r in peak_rows if r and len(r) >= 2]\n    chart_data = [r[1] for r in peak_rows if r and len(r) >= 2]\n\n    contributors = analytics.get('concurrency_peak_contributors', []) or []\n    contrib_section = ''\n    if contributors:\n        if isinstance(contributors[0], dict):\n            contrib_section = render_table(list(contributors[0].keys()), contributors, 'table-peak-contrib', 'gov-table')\n        else:\n            contrib_section = render_table(['USERID'], [[c] for c in contributors], 'table-peak-contrib', 'gov-table')\n\n    # Expose series to JS through data attributes (simple & robust)\n    labels_json = json.dumps(chart_labels, ensure_ascii=False)\n    data_json = json.dumps(chart_data, ensure_ascii=False)"
new1 = "    # Users series (capacidade)\n    peak_hours_users = analytics.get('concurrency_peak_users_hours', []) or []\n    users_rows = []\n    if isinstance(peak_hours_users, dict):\n        users_rows = [[k, v] for k, v in sorted(peak_hours_users.items())]\n    elif isinstance(peak_hours_users, list):\n        for entry in peak_hours_users:\n            if isinstance(entry, (list, tuple)) and len(entry) >= 2:\n                users_rows.append([entry[0], entry[1]])\n            elif isinstance(entry, dict):\n                hour = entry.get('hour') or entry.get('ts') or entry.get('time')\n                val = entry.get('value') or entry.get('users') or entry.get('count')\n                users_rows.append([hour, val])\n\n    users_labels = [r[0] for r in users_rows if r and len(r) >= 2]\n    users_data = [r[1] for r in users_rows if r and len(r) >= 2]\n    points_labels = [r[0] for r in peak_rows if r and len(r) >= 2]\n    points_data = [r[1] for r in peak_rows if r and len(r) >= 2]\n\n    # Fallback: se não vierem dados de usuários (capacidade), desenha com AppPoints (consumo)\n    used_fallback_app_points = False\n    if (not users_data) and peak_rows:\n        users_labels = [r[0] for r in peak_rows if r and len(r) >= 2]\n        users_data = [r[1] for r in peak_rows if r and len(r) >= 2]\n        points_labels = [r[0] for r in peak_rows if r and len(r) >= 2]\n        points_data = [r[1] for r in peak_rows if r and len(r) >= 2]\n        used_fallback_app_points = True\n\n    contributors = analytics.get('concurrency_peak_contributors', []) or []\n    contrib_section = ''\n    if contributors:\n        if isinstance(contributors[0], dict):\n            contrib_section = render_table(list(contributors[0].keys()), contributors, 'table-peak-contrib', 'gov-table')\n        else:\n            contrib_section = render_table(['USERID'], [[c] for c in contributors], 'table-peak-contrib', 'gov-table')\n\n    # Expose series to JS through data attributes (simple & robust)\n    labels_json = json.dumps(users_labels, ensure_ascii=False)\n    data_json = json.dumps(users_data, ensure_ascii=False)\n    points_labels_json = json.dumps(points_labels, ensure_ascii=False)\n    points_data_json = json.dumps(points_data, ensure_ascii=False)";
if old1 not in t: print('FAIL 1'); sys.exit(1)
t = t.replace(old1, new1); print('Patch 1 ok')

old2 = "                        data-labels='{labels_json}'\n                        data-data='{data_json}'></canvas>"
new2 = "                        data-labels='{labels_json}'\n                        data-data='{data_json}'\n                        data-points-labels='{points_labels_json}'\n                        data-points-data='{points_data_json}'></canvas>"
if old2 not in t: print('FAIL 2'); sys.exit(1)
t = t.replace(old2, new2); print('Patch 2 ok')

t = t.replace('Passe o mouse para ver quantos usuários simultâneos/valor de pico estavam ativos no horário.', 'Passe o mouse para ver usuários simultâneos e consumo de AppPoints no mesmo horário.'); print('Patch 3 ok')

with open(p, 'w', encoding='utf-8') as f: f.write(t)
print('PART1 OK')