-- MAXIMO.LOCKOUT definição

CREATE TABLE "MAXIMO  "."LOCKOUT"  (
		  "LOCKOUTID" BIGINT NOT NULL , 
		  "DESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "LOCATION" VARGRAPHIC(14 CODEUNITS16) , 
		  "ASSETNUM" VARGRAPHIC(20 CODEUNITS16) , 
		  "DEVICEDESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "REQUIREDSTATE" VARGRAPHIC(19 CODEUNITS16) , 
		  "LCK01" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK02" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK03" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK04" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK05" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK06" DECIMAL(10,2) , 
		  "LCK07" TIMESTAMP , 
		  "LCK08" DECIMAL(15,2) , 
		  "LCK09" VARGRAPHIC(12 CODEUNITS16) , 
		  "LCK10" BIGINT , 
		  "ORGID" VARGRAPHIC(8 CODEUNITS16) NOT NULL , 
		  "SITEID" VARGRAPHIC(10 CODEUNITS16) NOT NULL , 
		  "LANGCODE" VARGRAPHIC(4 CODEUNITS16) NOT NULL , 
		  "HASLD" BIGINT NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL )   
		 IN "MAXDATA" INDEX IN "MAXINDEX"  
		 ORGANIZE BY ROW;

CREATE UNIQUE INDEX "MAXIMO  "."LOCKOUT_NDX1" ON "MAXIMO  "."LOCKOUT" 
		("SITEID" ASC,
		 "LOCKOUTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "MAXIMO  "."LOCKOUT" 
	ADD PRIMARY KEY
		("LOCKOUTID")
	ENFORCED;

CREATE TRIGGER LOCKOUT_T NO CASCADE BEFORE INSERT ON LOCKOUT REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

CREATE TRIGGER LOCKOUT_U NO CASCADE BEFORE UPDATE ON LOCKOUT REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

GRANT ALTER ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT DELETE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT INDEX ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT INSERT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT SELECT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT UPDATE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT REFERENCES ON TABLE "MAXIMO  "."LOCKOUT" TO USER "CDCADMIN";

GRANT CONTROL ON TABLE "MAXIMO  "."LOCKOUT" TO USER "MAXIMO  ";

GRANT SELECT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "MAXORA  ";

GRANT ALTER ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT DELETE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT INDEX ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT INSERT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT SELECT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT UPDATE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT REFERENCES ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_DATALAKE";

GRANT ALTER ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT DELETE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT INDEX ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT INSERT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT SELECT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT UPDATE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT REFERENCES ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_LIVE";

GRANT ALTER ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT DELETE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT INDEX ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT INSERT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT SELECT ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT UPDATE ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT REFERENCES ON TABLE "MAXIMO  "."LOCKOUT" TO USER "RAC_SMART";

GRANT CONTROL ON INDEX "MAXIMO  "."LOCKOUT_NDX1" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL251206163704290" TO USER "MAXIMO  ";