-- MAXIMO.OOG_ALERT definição

CREATE TABLE "MAXIMO  "."OOG_ALERT"  (
		  "ACTIONTYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "ALERTID" VARCHAR(20 OCTETS) , 
		  "CHANGEBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "CREATEDBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "CREATIONDATE" TIMESTAMP , 
		  "DEPARTMENT" VARGRAPHIC(10 CODEUNITS16) , 
		  "DESCRIPTION" VARGRAPHIC(300 CODEUNITS16) , 
		  "DURATION" DOUBLE , 
		  "HASLD" BIGINT NOT NULL , 
		  "LANGCODE" VARGRAPHIC(4 CODEUNITS16) NOT NULL , 
		  "MODEL" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_ALERTID" BIGINT NOT NULL , 
		  "OOG_JOB_CLASS" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_JOB_GRADE" VARGRAPHIC(60 CODEUNITS16) , 
		  "ORGID" VARGRAPHIC(8 CODEUNITS16) , 
		  "ORIGIN" VARGRAPHIC(72 CODEUNITS16) , 
		  "ORIGINDATE" DATE , 
		  "ORIGINID" VARGRAPHIC(72 CODEUNITS16) , 
		  "ORIGINTYPE" VARGRAPHIC(72 CODEUNITS16) , 
		  "OWNER" VARGRAPHIC(36 CODEUNITS16) , 
		  "RECEIPTDATE" DATE , 
		  "REFERENCES" VARGRAPHIC(300 CODEUNITS16) , 
		  "RSRNUMBER" VARGRAPHIC(12 CODEUNITS16) , 
		  "STATUS" VARGRAPHIC(50 CODEUNITS16) , 
		  "STATUSDATE" TIMESTAMP , 
		  "SUBJECT" VARGRAPHIC(300 CODEUNITS16) , 
		  "TARGCOMPDATE" TIMESTAMP , 
		  "TARGSTARTDATE" TIMESTAMP , 
		  "VALIDATEDBY" VARGRAPHIC(120 CODEUNITS16) , 
		  "WODESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "WORKTYPE" VARGRAPHIC(10 CODEUNITS16) , 
		  "WOUA" VARGRAPHIC(19 CODEUNITS16) , 
		  "OOG_WARRANTYALERT" BIGINT NOT NULL , 
		  "OOG_WORKHOURS" DOUBLE , 
		  "OOG_EVENTCODE" VARGRAPHIC(14 CODEUNITS16) , 
		  "PLUSGRFWNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "RESNUMBER" VARGRAPHIC(24 CODEUNITS16) , 
		  "OOG_OBSOLESCENCE" BIGINT NOT NULL , 
		  "OOG_TYPE" VARGRAPHIC(18 CODEUNITS16) , 
		  "OOG_APLANNER" VARGRAPHIC(36 CODEUNITS16) , 
		  "OOG_CREATEDFROM" VARGRAPHIC(14 CODEUNITS16) , 
		  "OOG_DISCLOSURE" BIGINT NOT NULL , 
		  "OOG_ESTCOST" DECIMAL(10,2) , 
		  "OOG_ESTLABCOST" DECIMAL(10,2) , 
		  "OOG_ESTMATCOST" DECIMAL(10,2) , 
		  "OOG_ESTSERVCOST" DECIMAL(10,2) , 
		  "OOG_ESTTOOLCOST" DECIMAL(10,2) , 
		  "OOG_INITIALISSUE" VARGRAPHIC(4 CODEUNITS16) , 
		  "OOG_PLUSGCFWNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_REMARKS" VARGRAPHIC(240 CODEUNITS16) , 
		  "ROWSTAMP" BIGINT NOT NULL )   
		 DATA CAPTURE CHANGES  
		 IN "MAXDATA" INDEX IN "MAXINDEX"  
		 ORGANIZE BY ROW;

CREATE UNIQUE INDEX "MAXIMO  "."OOG_ALERT_NDX3" ON "MAXIMO  "."OOG_ALERT" 
		("ALERTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "MAXIMO  "."OOG_ALERT" 
	ADD PRIMARY KEY
		("OOG_ALERTID")
	ENFORCED;

CREATE TRIGGER OOG_ALERT_T NO CASCADE BEFORE INSERT ON OOG_ALERT REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

CREATE TRIGGER OOG_ALERT_U NO CASCADE BEFORE UPDATE ON OOG_ALERT REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

GRANT ALTER ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT DELETE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT INDEX ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT INSERT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT SELECT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT UPDATE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT REFERENCES ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "CDCADMIN";

GRANT CONTROL ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "MAXIMO  ";

GRANT SELECT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "MAXORA  ";

GRANT ALTER ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT DELETE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT INDEX ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT INSERT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT SELECT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT UPDATE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT REFERENCES ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_DATALAKE";

GRANT ALTER ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT DELETE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT INDEX ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT INSERT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT SELECT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT UPDATE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT REFERENCES ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_LIVE";

GRANT ALTER ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT DELETE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT INDEX ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT INSERT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT SELECT ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT UPDATE ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT REFERENCES ON TABLE "MAXIMO  "."OOG_ALERT" TO USER "RAC_SMART";

GRANT CONTROL ON INDEX "MAXIMO  "."OOG_ALERT_NDX3" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL251206163741970" TO USER "MAXIMO  ";