-- MAXIMO.PLUSGMOCRVLST definição

CREATE TABLE "MAXIMO  "."PLUSGMOCRVLST"  (
		  "PLUSGMOCRVLSTID" BIGINT NOT NULL , 
		  "REVIEWER" VARGRAPHIC(36 CODEUNITS16) NOT NULL , 
		  "REVIEWED" BIGINT NOT NULL , 
		  "SIGNOFFDATE" TIMESTAMP , 
		  "COMMENTS" VARGRAPHIC(240 CODEUNITS16) , 
		  "WONUM" VARGRAPHIC(20 CODEUNITS16) NOT NULL , 
		  "ORGID" VARGRAPHIC(8 CODEUNITS16) NOT NULL , 
		  "SITEID" VARGRAPHIC(10 CODEUNITS16) NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL )   
		 DATA CAPTURE CHANGES  
		 IN "MAXDATA" INDEX IN "MAXINDEX"  
		 ORGANIZE BY ROW;

CREATE UNIQUE INDEX "MAXIMO  "."PLUSGMOCRVLST_NDX2" ON "MAXIMO  "."PLUSGMOCRVLST" 
		("SITEID" ASC,
		 "WONUM" ASC,
		 "REVIEWER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "MAXIMO  "."PLUSGMOCRVLST" 
	ADD PRIMARY KEY
		("PLUSGMOCRVLSTID")
	ENFORCED;

CREATE TRIGGER PLUSGMOCRVLST_T NO CASCADE BEFORE INSERT ON PLUSGMOCRVLST
REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL
FOR MAXSEQ;

CREATE TRIGGER PLUSGMOCRVLST_U NO CASCADE BEFORE UPDATE ON PLUSGMOCRVLST
REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL
FOR MAXSEQ;

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "CDCADMIN";

GRANT CONTROL ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "MAXIMO  ";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "MAXORA  ";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_DATALAKE";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_LIVE";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGMOCRVLST" TO USER "RAC_SMART";

GRANT CONTROL ON INDEX "MAXIMO  "."PLUSGMOCRVLST_NDX2" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL251206163811930" TO USER "MAXIMO  ";