-- MAXIMO.PLUSGPERMITWORK definição

CREATE TABLE "MAXIMO  "."PLUSGPERMITWORK"  (
		  "PERMITWORKNUM" VARGRAPHIC(10 CODEUNITS16) NOT NULL , 
		  "DESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "EXTDESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "CHANGEDATE" TIMESTAMP , 
		  "CHANGEDBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "ORGID" VARGRAPHIC(8 CODEUNITS16) NOT NULL , 
		  "SITEID" VARGRAPHIC(10 CODEUNITS16) NOT NULL , 
		  "OWNER" VARGRAPHIC(36 CODEUNITS16) , 
		  "OWNERGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "STATUS" VARGRAPHIC(20 CODEUNITS16) NOT NULL , 
		  "STATUSDATE" TIMESTAMP NOT NULL , 
		  "DETAILS" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGPERTYPEID" BIGINT , 
		  "PERTYPENUM" VARGRAPHIC(10 CODEUNITS16) , 
		  "PERMITLEVEL" VARGRAPHIC(19 CODEUNITS16) , 
		  "EXTNUM" BIGINT NOT NULL , 
		  "TEMPLATE" BIGINT NOT NULL , 
		  "REQUIREDDATE" TIMESTAMP , 
		  "WORKINGHOURS" VARGRAPHIC(24 CODEUNITS16) , 
		  "PERMITVALIDITY" BIGINT , 
		  "PERMITUNITS" VARGRAPHIC(19 CODEUNITS16) , 
		  "LOCATIONSID" BIGINT , 
		  "LOCATION" VARGRAPHIC(14 CODEUNITS16) , 
		  "ASSETID" BIGINT , 
		  "ASSETNUM" VARGRAPHIC(20 CODEUNITS16) , 
		  "PERMITUNIT" VARGRAPHIC(19 CODEUNITS16) , 
		  "WORKORDERID" BIGINT , 
		  "WOTASKID" BIGINT , 
		  "ACTIVITYCATEGORY" VARGRAPHIC(36 CODEUNITS16) , 
		  "REQUESTOR" VARGRAPHIC(36 CODEUNITS16) , 
		  "THIRDPARTY" BIGINT , 
		  "COMPANIESID" BIGINT , 
		  "CROSSAREACOUNTSIG" BIGINT , 
		  "CONFSPACEAUTHID" BIGINT , 
		  "CONFSPACEAUTH" VARGRAPHIC(36 CODEUNITS16) , 
		  "ISOCERT" BIGINT NOT NULL , 
		  "SPECISOLATION" VARGRAPHIC(36 CODEUNITS16) , 
		  "ISOREASON" VARGRAPHIC(240 CODEUNITS16) , 
		  "RISKASSESSREQ" BIGINT , 
		  "MASTERPERMIT" BIGINT , 
		  "SITECHECKED" BIGINT , 
		  "SITECHECKEDBYID" BIGINT , 
		  "TBTCOMPLETED" BIGINT , 
		  "TBTCOMPLETEDBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "SITECHECKEDDATE" TIMESTAMP , 
		  "TBTCOMPLETEDDATE" TIMESTAMP , 
		  "CONTGASTESTREQD" BIGINT , 
		  "GASTESTREPEATFREQ" VARGRAPHIC(24 CODEUNITS16) , 
		  "TOOLBOXCOMMENTS" VARGRAPHIC(240 CODEUNITS16) , 
		  "WORKCOMPLETED" BIGINT , 
		  "WORKCOMPLETEDAUTHID" BIGINT , 
		  "SAFECONDITION" BIGINT , 
		  "SAFECONDITIONAUTHID" BIGINT , 
		  "ISOLATIONSREMOVED" BIGINT , 
		  "ISOLATIONSREMOVEDAUTHID" BIGINT , 
		  "PRODUCTION" BIGINT , 
		  "PRODUCTIONAUTHID" BIGINT , 
		  "INHIBITSREMOVED" BIGINT , 
		  "INHIBITSREMOVEDAUTHID" BIGINT , 
		  "WORKCOMPLETEDDATE" TIMESTAMP , 
		  "SAFECONDITIONDATE" TIMESTAMP , 
		  "ISOLATIONSREMOVEDDATE" TIMESTAMP , 
		  "PRODUCTIONDATE" TIMESTAMP , 
		  "INHIBITSREMOVEDDATE" TIMESTAMP , 
		  "CLOSUREREVIEWERID" BIGINT , 
		  "CLOSUREREVDATE" TIMESTAMP , 
		  "CLOSURECOMMENTS" VARGRAPHIC(240 CODEUNITS16) , 
		  "CLOSURELESSONSLEARNED" BIGINT , 
		  "CLOSUREAUDITREQUIRED" BIGINT , 
		  "CLOSURESITECLEARED" BIGINT , 
		  "PLUSGRISKASSESSID" BIGINT , 
		  "RISKCOMMENTS" VARGRAPHIC(240 CODEUNITS16) , 
		  "RISKCOPIEDFROMWO" BIGINT NOT NULL , 
		  "RISKREVISED" BIGINT NOT NULL , 
		  "ATTACHEDDOC" BIGINT NOT NULL , 
		  "SELFISOLATION" BIGINT NOT NULL , 
		  "ROUTESID" BIGINT , 
		  "PLUSGPROCEDUREID" BIGINT , 
		  "REFDRAWING" VARGRAPHIC(24 CODEUNITS16) , 
		  "MASTERLOCKBOX" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGPERMITWORKID" BIGINT NOT NULL , 
		  "HASLD" BIGINT NOT NULL , 
		  "LANGCODE" VARGRAPHIC(4 CODEUNITS16) NOT NULL , 
		  "PLUSGAUDITID" BIGINT , 
		  "SHIFT" VARGRAPHIC(36 CODEUNITS16) , 
		  "CLOSUREENTERPMTRGT" BIGINT , 
		  "PLUSGHAZARDSUMM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGTOTALSCORE" BIGINT , 
		  "CREATEDATE" TIMESTAMP , 
		  "PLUSGGROUPCODE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PTWCLASS" VARGRAPHIC(19 CODEUNITS16) , 
		  "RESERVED1" VARGRAPHIC(19 CODEUNITS16) , 
		  "LONGTERMISO" BIGINT NOT NULL , 
		  "OOG_THIRDPARTY" BIGINT , 
		  "OOG_THIRDPARTYNAME" VARGRAPHIC(180 CODEUNITS16) , 
		  "OOG_CONFLITACTIVITIES" VARGRAPHIC(480 CODEUNITS16) , 
		  "OOG_CLOSURESITECLEARED" BIGINT , 
		  "OOG_CLOSUREREVIEWER" VARGRAPHIC(36 CODEUNITS16) , 
		  "OOG_CLOSUREREVDATE" TIMESTAMP , 
		  "OOG_VERIFICATIONSUPERVISION" BIGINT , 
		  "OOG_PURGA" BIGINT , 
		  "OOG_PTWAREA" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_ISCRITICAL" BIGINT , 
		  "OOG_THIRDEQUIPSYS" VARGRAPHIC(120 CODEUNITS16) , 
		  "OOG_EQUIPSYSTOUT" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_GASDETECTOR" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_INHIBITEDSENSORS" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_SENSORSLIST" VARGRAPHIC(600 CODEUNITS16) , 
		  "OOG_CONFSPACENUM" VARGRAPHIC(100 CODEUNITS16) , 
		  "OOG_FREQUENCY" BIGINT , 
		  "OOG_PERIODICVERIFICATION" BIGINT NOT NULL , 
		  "OOG_VALIDUNTIL" TIMESTAMP , 
		  "OOG_APPROVAL_DATE" TIMESTAMP , 
		  "OOG_DESCTYPE" VARGRAPHIC(720 CODEUNITS16) , 
		  "OOG_VALVE_NUMBER" VARGRAPHIC(720 CODEUNITS16) , 
		  "OOG_WORKEXPERIENCE" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_CHANGESTATUS" VARGRAPHIC(120 CODEUNITS16) , 
		  "HISTORYFLAG" BIGINT NOT NULL , 
		  "PLUSGSAFETYCRIT" BIGINT , 
		  "MASTERLOCKINUSE" BIGINT NOT NULL , 
		  "MASTERLOCKBOXKEY" VARGRAPHIC(18 CODEUNITS16) , 
		  "PLUSGCONTROLSSUMM" VARGRAPHIC(240 CODEUNITS16) , 
		  "LOCKRETURNED" BIGINT NOT NULL , 
		  "PLUSGMETHODSTATEMENT" VARGRAPHIC(240 CODEUNITS16) , 
		  "INSPFORMNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "INSPFORMREV" BIGINT , 
		  "RESULTNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "ORIGRESULTNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_HOTWORK" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_RISKEC" VARGRAPHIC(36 CODEUNITS16) , 
		  "OOG_SIMOOPS" VARGRAPHIC(5 CODEUNITS16) , 
		  "OOG_SIMOOPS_DETAIL" BIGINT NOT NULL , 
		  "OOG_CLOSUREREASON" VARGRAPHIC(240 CODEUNITS16) , 
		  "OOG_QUESTION01" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION02" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION03" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION04" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION05" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION06" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION07" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTION1" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_QUESTIONOBS" VARGRAPHIC(480 CODEUNITS16) , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "OOG_QUESTION01_OTHERS" VARCHAR(600 OCTETS) , 
		  "OOG_QUESTION02_OTHERS" VARCHAR(600 OCTETS) , 
		  "OOG_QUESTION03_OTHERS" VARCHAR(600 OCTETS) , 
		  "OOG_QUESTION04_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION05_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION08" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION08_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION09" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION09_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION10" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION10_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION11" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION12" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION12_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION13" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION14" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION14_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION15" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION15_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION16" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION16_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_QUESTION17" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION18" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION19" VARCHAR(60 OCTETS) , 
		  "OOG_QUESTION19_OTHERS" VARCHAR(400 OCTETS) , 
		  "OOG_TEAMPLANNINGDECL" INTEGER NOT NULL )   
		 DATA CAPTURE CHANGES  
		 IN "MAXDATA" INDEX IN "MAXINDEX"  
		 ORGANIZE BY ROW;

CREATE UNIQUE INDEX "MAXIMO  "."PLUSGPERMITWO_NDX1" ON "MAXIMO  "."PLUSGPERMITWORK" 
		("ORGID" ASC,
		 "SITEID" ASC,
		 "PERMITWORKNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "MAXIMO  "."PLUSGPERMITWORK" 
	ADD PRIMARY KEY
		("PLUSGPERMITWORKID")
	ENFORCED;

CREATE TRIGGER PLUSGPERMITWORK_T NO CASCADE BEFORE INSERT ON PLUSGPERMITWORK
REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL
FOR MAXSEQ;

CREATE TRIGGER PLUSGPERMITWORK_U NO CASCADE BEFORE UPDATE ON PLUSGPERMITWORK
REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL
FOR MAXSEQ;

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "CDCADMIN";

GRANT CONTROL ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "MAXIMO  ";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "MAXORA  ";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_DATALAKE";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_LIVE";

GRANT ALTER ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT DELETE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT INDEX ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT INSERT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT SELECT ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT UPDATE ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT REFERENCES ON TABLE "MAXIMO  "."PLUSGPERMITWORK" TO USER "RAC_SMART";

GRANT CONTROL ON INDEX "MAXIMO  "."PLUSGPERMITWO_NDX1" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL251206163812860" TO USER "MAXIMO  ";