-- MAXIMO.WORKORDER definição

CREATE TABLE "MAXIMO  "."WORKORDER"  (
		  "WONUM" VARGRAPHIC(20 CODEUNITS16) NOT NULL , 
		  "PARENT" VARGRAPHIC(24 CODEUNITS16) , 
		  "STATUS" VARGRAPHIC(16 CODEUNITS16) NOT NULL , 
		  "STATUSDATE" TIMESTAMP NOT NULL , 
		  "WORKTYPE" VARGRAPHIC(10 CODEUNITS16) , 
		  "DESCRIPTION" VARGRAPHIC(120 CODEUNITS16) , 
		  "ASSETNUM" VARGRAPHIC(20 CODEUNITS16) , 
		  "LOCATION" VARGRAPHIC(14 CODEUNITS16) , 
		  "JPNUM" VARGRAPHIC(100 CODEUNITS16) , 
		  "FAILDATE" TIMESTAMP , 
		  "CHANGEBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "CHANGEDATE" TIMESTAMP , 
		  "ESTDUR" DOUBLE NOT NULL , 
		  "ESTLABHRS" DOUBLE NOT NULL , 
		  "ESTMATCOST" DECIMAL(10,2) NOT NULL , 
		  "ESTLABCOST" DECIMAL(10,2) NOT NULL , 
		  "ESTTOOLCOST" DECIMAL(10,2) NOT NULL , 
		  "PMNUM" VARGRAPHIC(100 CODEUNITS16) , 
		  "ACTLABHRS" DOUBLE NOT NULL , 
		  "ACTMATCOST" DECIMAL(10,2) NOT NULL , 
		  "ACTLABCOST" DECIMAL(10,2) NOT NULL , 
		  "ACTTOOLCOST" DECIMAL(10,2) NOT NULL , 
		  "HASCHILDREN" BIGINT NOT NULL , 
		  "OUTLABCOST" DECIMAL(10,2) NOT NULL , 
		  "OUTMATCOST" DECIMAL(10,2) NOT NULL , 
		  "OUTTOOLCOST" DECIMAL(10,2) NOT NULL , 
		  "HISTORYFLAG" BIGINT NOT NULL , 
		  "CONTRACT" VARGRAPHIC(72 CODEUNITS16) , 
		  "WOPRIORITY" BIGINT , 
		  "TARGCOMPDATE" TIMESTAMP , 
		  "TARGSTARTDATE" TIMESTAMP , 
		  "WOEQ1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ3" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ4" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ5" DECIMAL(10,2) , 
		  "WOEQ6" TIMESTAMP , 
		  "WOEQ7" DECIMAL(15,2) , 
		  "WOEQ8" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ9" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ10" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ11" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOEQ12" DECIMAL(10,2) , 
		  "REPORTEDBY" VARGRAPHIC(74 CODEUNITS16) , 
		  "REPORTDATE" TIMESTAMP , 
		  "PHONE" VARGRAPHIC(144 CODEUNITS16) , 
		  "PROBLEMCODE" VARGRAPHIC(10 CODEUNITS16) , 
		  "CALENDAR" VARGRAPHIC(10 CODEUNITS16) , 
		  "DOWNTIME" BIGINT NOT NULL , 
		  "ACTSTART" TIMESTAMP , 
		  "ACTFINISH" TIMESTAMP , 
		  "SCHEDSTART" TIMESTAMP , 
		  "SCHEDFINISH" TIMESTAMP , 
		  "REMDUR" DOUBLE , 
		  "CREWID" VARGRAPHIC(14 CODEUNITS16) , 
		  "SUPERVISOR" VARGRAPHIC(36 CODEUNITS16) , 
		  "WOEQ13" TIMESTAMP , 
		  "WOEQ14" DECIMAL(15,2) , 
		  "WOJP1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJP2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJP3" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJP4" DECIMAL(10,2) , 
		  "WOJP5" TIMESTAMP , 
		  "WOL1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOL2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOL3" DECIMAL(10,2) , 
		  "WOL4" TIMESTAMP , 
		  "WOLABLNK" VARGRAPHIC(48 CODEUNITS16) , 
		  "RESPONDBY" TIMESTAMP , 
		  "ASSETLOCPRIORITY" BIGINT , 
		  "CALCPRIORITY" BIGINT , 
		  "CHARGESTORE" BIGINT NOT NULL , 
		  "FAILURECODE" VARGRAPHIC(10 CODEUNITS16) , 
		  "WOLO1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO3" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO4" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO5" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO6" DECIMAL(10,2) , 
		  "WOLO7" TIMESTAMP , 
		  "WOLO8" DECIMAL(15,2) , 
		  "WOLO9" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOLO10" BIGINT , 
		  "GLACCOUNT" VARGRAPHIC(90 CODEUNITS16) , 
		  "ESTSERVCOST" DECIMAL(10,2) NOT NULL , 
		  "ACTSERVCOST" DECIMAL(10,2) NOT NULL , 
		  "DISABLED" BIGINT NOT NULL , 
		  "ESTATAPPRLABHRS" DOUBLE NOT NULL , 
		  "ESTATAPPRLABCOST" DECIMAL(10,2) NOT NULL , 
		  "ESTATAPPRMATCOST" DECIMAL(10,2) NOT NULL , 
		  "ESTATAPPRTOOLCOST" DECIMAL(10,2) NOT NULL , 
		  "ESTATAPPRSERVCOST" DECIMAL(10,2) NOT NULL , 
		  "WOSEQUENCE" BIGINT , 
		  "HASFOLLOWUPWORK" BIGINT NOT NULL , 
		  "WORTS1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WORTS2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WORTS3" VARGRAPHIC(12 CODEUNITS16) , 
		  "WORTS4" TIMESTAMP , 
		  "WORTS5" DECIMAL(15,2) , 
		  "SOURCESYSID" VARGRAPHIC(12 CODEUNITS16) , 
		  "OWNERSYSID" VARGRAPHIC(12 CODEUNITS16) , 
		  "PMDUEDATE" DATE , 
		  "PMEXTDATE" DATE , 
		  "PMNEXTDUEDATE" DATE , 
		  "WORKLOCATION" VARGRAPHIC(14 CODEUNITS16) , 
		  "EXTERNALREFID" VARGRAPHIC(12 CODEUNITS16) , 
		  "SENDERSYSID" VARGRAPHIC(60 CODEUNITS16) , 
		  "FINCNTRLID" VARGRAPHIC(10 CODEUNITS16) , 
		  "GENERATEDFORPO" VARGRAPHIC(30 CODEUNITS16) , 
		  "GENFORPOLINEID" BIGINT , 
		  "ORGID" VARGRAPHIC(8 CODEUNITS16) NOT NULL , 
		  "SITEID" VARGRAPHIC(10 CODEUNITS16) NOT NULL , 
		  "TASKID" BIGINT , 
		  "INSPECTOR" VARGRAPHIC(36 CODEUNITS16) , 
		  "MEASUREMENTVALUE" DECIMAL(15,3) , 
		  "MEASUREDATE" TIMESTAMP , 
		  "OBSERVATION" VARGRAPHIC(240 CODEUNITS16) , 
		  "POINTNUM" VARGRAPHIC(20 CODEUNITS16) , 
		  "WOJO1" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO2" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO3" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO4" DECIMAL(15,2) , 
		  "WOJO5" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO6" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO7" VARGRAPHIC(12 CODEUNITS16) , 
		  "WOJO8" VARGRAPHIC(12 CODEUNITS16) , 
		  "ISTASK" BIGINT NOT NULL , 
		  "WOCLASS" VARGRAPHIC(19 CODEUNITS16) NOT NULL , 
		  "ONBEHALFOF" VARGRAPHIC(74 CODEUNITS16) , 
		  "VENDOR" VARGRAPHIC(300 CODEUNITS16) , 
		  "ORIGRECORDCLASS" VARGRAPHIC(19 CODEUNITS16) , 
		  "ORIGRECORDID" VARGRAPHIC(24 CODEUNITS16) , 
		  "JUSTIFYPRIORITY" VARGRAPHIC(60 CODEUNITS16) , 
		  "RISK" VARGRAPHIC(12 CODEUNITS16) , 
		  "ENVIRONMENT" VARGRAPHIC(60 CODEUNITS16) , 
		  "BACKOUTPLAN" VARGRAPHIC(60 CODEUNITS16) , 
		  "WOACCEPTSCHARGES" BIGINT NOT NULL , 
		  "OWNER" VARGRAPHIC(36 CODEUNITS16) , 
		  "CLASSSTRUCTUREID" VARGRAPHIC(24 CODEUNITS16) , 
		  "PARENTCHGSSTATUS" BIGINT NOT NULL , 
		  "OWNERGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "COMMODITYGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "COMMODITY" VARGRAPHIC(10 CODEUNITS16) , 
		  "WORKORDERID" BIGINT NOT NULL , 
		  "WHOMISCHANGEFOR" VARGRAPHIC(24 CODEUNITS16) , 
		  "REASONFORCHANGE" VARGRAPHIC(24 CODEUNITS16) , 
		  "VERIFICATION" VARGRAPHIC(24 CODEUNITS16) , 
		  "PERSONGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "LEAD" VARGRAPHIC(36 CODEUNITS16) , 
		  "LANGCODE" VARGRAPHIC(4 CODEUNITS16) NOT NULL , 
		  "INTERRUPTIBLE" BIGINT NOT NULL , 
		  "WOGROUP" VARGRAPHIC(24 CODEUNITS16) , 
		  "HASLD" BIGINT NOT NULL , 
		  "ROUTE" VARGRAPHIC(120 CODEUNITS16) , 
		  "ROUTESTOPID" BIGINT , 
		  "CINUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "JOBTASKID" BIGINT , 
		  "WOISSWAP" BIGINT NOT NULL , 
		  "NEWCHILDCLASS" VARGRAPHIC(19 CODEUNITS16) NOT NULL , 
		  "SUSPENDFLOW" BIGINT NOT NULL , 
		  "FLOWCONTROLLED" BIGINT NOT NULL , 
		  "FLOWACTIONASSIST" BIGINT NOT NULL , 
		  "LAUNCHENTRYNAME" VARGRAPHIC(38 CODEUNITS16) , 
		  "TARGETDESC" VARGRAPHIC(120 CODEUNITS16) , 
		  "FLOWACTION" VARGRAPHIC(36 CODEUNITS16) , 
		  "FIRSTAPPRSTATUS" VARGRAPHIC(19 CODEUNITS16) , 
		  "CALCORGID" VARGRAPHIC(10 CODEUNITS16) , 
		  "CALCCALENDAR" VARGRAPHIC(10 CODEUNITS16) , 
		  "CALCSHIFT" VARGRAPHIC(10 CODEUNITS16) , 
		  "REPFACSITEID" VARGRAPHIC(12 CODEUNITS16) , 
		  "REPAIRFACILITY" VARGRAPHIC(14 CODEUNITS16) , 
		  "GENFORPOREVISION" BIGINT , 
		  "STOREROOMMTLSTATUS" VARGRAPHIC(24 CODEUNITS16) , 
		  "DIRISSUEMTLSTATUS" VARGRAPHIC(24 CODEUNITS16) , 
		  "WORKPACKMTLSTATUS" VARGRAPHIC(24 CODEUNITS16) , 
		  "IGNORESRMAVAIL" BIGINT NOT NULL , 
		  "IGNOREDIAVAIL" BIGINT NOT NULL , 
		  "ESTINTLABCOST" DECIMAL(10,2) , 
		  "ESTINTLABHRS" DOUBLE , 
		  "ESTOUTLABHRS" DOUBLE , 
		  "ESTOUTLABCOST" DECIMAL(10,2) , 
		  "ACTINTLABCOST" DECIMAL(10,2) , 
		  "ACTINTLABHRS" DOUBLE , 
		  "ACTOUTLABHRS" DOUBLE , 
		  "ACTOUTLABCOST" DECIMAL(10,2) , 
		  "ESTATAPPRINTLABCOST" DECIMAL(10,2) , 
		  "ESTATAPPRINTLABHRS" DOUBLE , 
		  "ESTATAPPROUTLABHRS" DOUBLE , 
		  "ESTATAPPROUTLABCOST" DECIMAL(10,2) , 
		  "ASSIGNEDOWNERGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "AVAILSTATUSDATE" TIMESTAMP , 
		  "LASTCOPYLINKDATE" TIMESTAMP , 
		  "PLUSCFREQUENCY" BIGINT , 
		  "PLUSCFREQUNIT" VARGRAPHIC(14 CODEUNITS16) , 
		  "PLUSCISMOBILE" BIGINT NOT NULL , 
		  "PLUSCJPREVNUM" BIGINT , 
		  "PLUSCLOOP" BIGINT NOT NULL , 
		  "PLUSCNEXTDATE" TIMESTAMP , 
		  "PLUSCOVERDUEDATE" TIMESTAMP , 
		  "PLUSCPHYLOC" VARGRAPHIC(300 CODEUNITS16) , 
		  "INCTASKSINSCHED" BIGINT NOT NULL , 
		  "SNECONSTRAINT" TIMESTAMP , 
		  "FNLCONSTRAINT" TIMESTAMP , 
		  "PLUSGMPOVERRIDECOD" VARGRAPHIC(14 CODEUNITS16) , 
		  "PLUSGCFWNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGRFWNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGMATRIXINDEX" BIGINT , 
		  "PLUSGMATRIXPRIOR" BIGINT , 
		  "PLUSGFUNCTION" VARGRAPHIC(29 CODEUNITS16) , 
		  "PLUSGMPOVERRIDE" BIGINT NOT NULL , 
		  "PLUSGSAFETYCRIT" BIGINT NOT NULL , 
		  "PLUSGTGTDATEMOD" BIGINT NOT NULL , 
		  "PLUSGREVIEWREQ" BIGINT NOT NULL , 
		  "PLUSGENVCRIT" BIGINT NOT NULL , 
		  "PLUSGCOMCRIT" BIGINT NOT NULL , 
		  "PLUSGBENNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGIMPTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGTEAMLEADID" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGPROJECTTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGANALYSISMETH" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGDEFECTREF" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGPROJECTPHASE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGPROBLEMSTMT" VARGRAPHIC(480 CODEUNITS16) , 
		  "PLUSGMISSIONSTMT" VARGRAPHIC(480 CODEUNITS16) , 
		  "PLUSGMEASTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGDEFECTKPI" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGDEFECTMETER" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGDEFMEASPT" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGTARGETDEFRT" DECIMAL(10,2) , 
		  "PLUSGESTATAPPRBEN" DECIMAL(10,2) , 
		  "PLUSGESTATAPPRCOST" DECIMAL(10,2) , 
		  "PLUSGREVIEWED" BIGINT NOT NULL , 
		  "PLUSGCRITTOQUAL" BIGINT NOT NULL , 
		  "PLUSGDEFMEASREQ" BIGINT NOT NULL , 
		  "PLUSGLOSSQUANTITY" DECIMAL(10,2) , 
		  "PLUSGLOSSUNITS" VARGRAPHIC(30 CODEUNITS16) , 
		  "PLUSGREFERENCE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGACTIONTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGACTIONSUMM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGAGREEDBY" VARGRAPHIC(74 CODEUNITS16) , 
		  "PLUSGACTAGREEDDATE" TIMESTAMP , 
		  "PLUSGACTIONSOURCE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGLOCK" BIGINT NOT NULL , 
		  "PLUSGACTCOMPLETED" BIGINT NOT NULL , 
		  "PLUSGACTEXTERNAL" BIGINT NOT NULL , 
		  "PLUSGPROJECTID" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGMOCDEFERRALID" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGMOCTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGCATEGORY" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGREQUIREDDATE" TIMESTAMP , 
		  "PLUSGDEFUNTILDATE" TIMESTAMP , 
		  "PLUSGTEMPUNTILDATE" TIMESTAMP , 
		  "PLUSGSCOPE" VARGRAPHIC(4800 CODEUNITS16) , 
		  "PLUSGJUSTIFICATION" VARGRAPHIC(4800 CODEUNITS16) , 
		  "PLUSGREVIEWERPHONE" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGREVIEWEREMAIL" VARGRAPHIC(120 CODEUNITS16) , 
		  "PLUSGREQUESTEMAIL" VARGRAPHIC(120 CODEUNITS16) , 
		  "PLUSGPMNUMREF" VARGRAPHIC(120 CODEUNITS16) , 
		  "PLUSGHIGHRISK" BIGINT NOT NULL , 
		  "PLUSGTEMP" BIGINT NOT NULL , 
		  "PLUSGCLOSREVBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGCLOSURECOMM" VARGRAPHIC(4800 CODEUNITS16) , 
		  "PLUSGCLOSREVDATE" TIMESTAMP , 
		  "PLUSGAARREQUIRED" BIGINT NOT NULL , 
		  "PLUSGDOCSATTACHED" BIGINT NOT NULL , 
		  "PLUSGIMPREQD" BIGINT NOT NULL , 
		  "PLUSGLESSLEARNED" BIGINT NOT NULL , 
		  "PLUSGPOSTACTCOMP" BIGINT NOT NULL , 
		  "PLUSGACTIONPRIOR" BIGINT , 
		  "PLUSGPERTYPEID" BIGINT , 
		  "PLUSGPERMITREFNO" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGAREAAUTH" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGISSUEAUTH" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGPERFAUTH" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGRISKASSESSID" BIGINT , 
		  "PLUSGRISKASSESSCOM" VARGRAPHIC(1200 CODEUNITS16) , 
		  "PLUSGSTAGEGATE" VARGRAPHIC(22 CODEUNITS16) , 
		  "PLUSGCOSTESTIMATE" DECIMAL(10,2) , 
		  "PLUSGFINCNTRLID" VARGRAPHIC(10 CODEUNITS16) , 
		  "PLUSGRISKASSCAT" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGSHIFTLOGID" BIGINT , 
		  "PLUSGCONTINPLAN" BIGINT NOT NULL , 
		  "PLUSGGROUPCODE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGGATEKEEPER" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGOPENOMUID" BIGINT , 
		  "PLUSGSCHEDDEV" BIGINT NOT NULL , 
		  "PLUSGREASONFORDEV" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGPROCEDUREID" BIGINT , 
		  "PLUSGFIELDREF" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGOPERATOR" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGCUSTREF" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGSALESORDER" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGWELLNAMESYS" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGWELLNAME" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGWELLSTATUS" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGWELLPURPOSE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGRIGTYPE" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGRIGNO" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGWELLBORE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGCOMPSTAGE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGTESTTYPE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGTESTCERT" BIGINT NOT NULL , 
		  "PLUSGCOMPPERTYPEID" BIGINT , 
		  "PLUSGTECHTYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGTECHAUTHORITY" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGDERRICKTYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGDRAWWORKSTYPE" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGDRIVETYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGCEMENTJOBTYPE" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGWELLFLUID" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGELEVATIONCODE" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGTUBULARASSY" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGPITTYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGASSACTIVITY" BIGINT NOT NULL , 
		  "PLUSGASSACTIVITYIMP" BIGINT NOT NULL , 
		  "PLUSGITEMID" BIGINT , 
		  "PLUSGSUBCODE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGSUBREMARKS" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGMICODE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGMIREMARKS" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGFAILMECH" BIGINT , 
		  "PLUSGFAILMECHREM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGFAILSUBDIV" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGFAILSUBDIVREM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGSAFETYFAILCAT" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGHARDFAILMODE" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGCCF" BIGINT , 
		  "NESTEDJPINPROCESS" BIGINT NOT NULL , 
		  "AMCREW" VARGRAPHIC(10 CODEUNITS16) , 
		  "CREWWORKGROUP" VARGRAPHIC(10 CODEUNITS16) , 
		  "REQASSTDWNTIME" BIGINT NOT NULL , 
		  "OOG_ASSETTAG" VARGRAPHIC(77 CODEUNITS16) , 
		  "OOG_JOB_CLASS" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_JOB_GRADE" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_JOB_PRIORITY" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_PRINTEDDATE" DATE , 
		  "OOG_STDACTNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_UA" VARGRAPHIC(19 CODEUNITS16) , 
		  "OOG_WORKREPORT" CLOB(1073741824 OCTETS) LOGGED NOT COMPACT , 
		  "OOG_IGNORESERVIRESERV" BIGINT NOT NULL , 
		  "OOG_DISCIPLINE" VARGRAPHIC(18 CODEUNITS16) , 
		  "ASSETCOUNTERID" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_VENDOR" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_CONCDATE" TIMESTAMP , 
		  "OOG_MANAREA" VARGRAPHIC(10 CODEUNITS16) , 
		  "OOG_STARTDATE" TIMESTAMP , 
		  "OOG_NEWVALIDITY" TIMESTAMP , 
		  "OOG_IMPLEMDATE" TIMESTAMP , 
		  "OOG_REASON" VARGRAPHIC(4800 CODEUNITS16) , 
		  "OOG_FAILURECLASS" VARGRAPHIC(240 CODEUNITS16) , 
		  "OOG_FAILURE" BIGINT NOT NULL , 
		  "OOG_FAILUREMODE" VARGRAPHIC(12 CODEUNITS16) , 
		  "OOG_SOLUTION" VARGRAPHIC(60 CODEUNITS16) , 
		  "OOG_CREDITCODE" VARGRAPHIC(120 CODEUNITS16) , 
		  "OOG_CREDITLINK" VARGRAPHIC(120 CODEUNITS16) , 
		  "OOG_DAYQUANTITY" DECIMAL(3,0) , 
		  "PLUSGAUDITID" BIGINT , 
		  "PLUSGCERTID" BIGINT , 
		  "PLUSGDETECTIONMETHOD" VARGRAPHIC(60 CODEUNITS16) , 
		  "PLUSGPOLICYID" BIGINT , 
		  "PLUSGPOLICYNUM" VARGRAPHIC(10 CODEUNITS16) , 
		  "PLUSGBARRIERFAILDETECT" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGBARRIERFAIL" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGHASSAFETYCRIT" BIGINT NOT NULL , 
		  "PLUSGSAFETYCRITELM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGFAILFIX" BIGINT NOT NULL , 
		  "PLUSGMIGRATIONREQ" BIGINT NOT NULL , 
		  "PLUSGCAPEX" BIGINT NOT NULL , 
		  "PLUSGPREPACTIV" BIGINT NOT NULL , 
		  "PLUSGPREPTYPE" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGPREPPHASE" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGPREPREF" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGSCENARIO" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGWORKBREAK" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGACTOWNERID" BIGINT , 
		  "PLUSGFREEZEDATE" TIMESTAMP , 
		  "PLUSGPREPAUDID" BIGINT , 
		  "PLUSGPREPARDNES" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGPREPACTPRI" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGDECISION" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGEVIDENCE" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGPERMITWORKID" BIGINT , 
		  "PLUSGFIXEDMEASVALUE" DECIMAL(15,3) , 
		  "PLUSGACTREQUIRED" BIGINT NOT NULL , 
		  "PLUSGPASS" BIGINT NOT NULL , 
		  "APPTREQUIRED" BIGINT NOT NULL , 
		  "AOS" BIGINT NOT NULL , 
		  "AMS" BIGINT NOT NULL , 
		  "LOS" BIGINT NOT NULL , 
		  "LMS" BIGINT NOT NULL , 
		  "INSPFORMNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGHAZARDUID" BIGINT , 
		  "PLUSGTECAUTTYPE" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGBYPTYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGBYPCAT" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGTAG" VARGRAPHIC(24 CODEUNITS16) , 
		  "PLUSGBYPUNIT" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGSAFECRIELEM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGMONMECH" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGLONGTERM" BIGINT , 
		  "PLUSGBYPVALIDITY" BIGINT , 
		  "PLUSGBYPUNITS" VARGRAPHIC(19 CODEUNITS16) , 
		  "PLUSGAUDITREQ" BIGINT , 
		  "PLUSGHAZARDSUMM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGTOTALSCORE" BIGINT , 
		  "PLUSGREVCOMMENTS" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGREVIEWBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGREVIEWBYID" BIGINT , 
		  "PLUSGSHIFTLOGNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "TEMPLATE" BIGINT NOT NULL , 
		  "PLUSGSHFTLOGENTRYID" BIGINT , 
		  "PLUSGREVACTSUMM" VARGRAPHIC(240 CODEUNITS16) , 
		  "PLUSGCOPYREVACTRSK" BIGINT , 
		  "ACTCATEGORY" VARGRAPHIC(22 CODEUNITS16) , 
		  "BULLETINBOARDID" VARGRAPHIC(12 CODEUNITS16) , 
		  "ADDIBULLETINDETAILS" VARGRAPHIC(4800 CODEUNITS16) , 
		  "REGULATIONID" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGREGULATIONID" BIGINT , 
		  "PLUSGCIID" BIGINT , 
		  "COMPANIESID" BIGINT , 
		  "COMPREFERENCE" VARGRAPHIC(38 CODEUNITS16) , 
		  "BULLETINTYPE" VARGRAPHIC(22 CODEUNITS16) , 
		  "BULLETINSRC" VARGRAPHIC(22 CODEUNITS16) , 
		  "PLUSGQUALITYCRITICAL" BIGINT NOT NULL , 
		  "PLUSGSAFMTGENTEREDDATE" TIMESTAMP , 
		  "PLUSGSAFMTGENTEREDBYID" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGSAFMTGENTEREDBYNAME" VARGRAPHIC(74 CODEUNITS16) , 
		  "PLUSGSAFMTGAGREEDBYID" VARGRAPHIC(36 CODEUNITS16) , 
		  "PLUSGSAFMTGAGREEDBYNAME" VARGRAPHIC(74 CODEUNITS16) , 
		  "PLUSGSAFMTGSUMMARY" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGPERTYPENUM" VARGRAPHIC(10 CODEUNITS16) , 
		  "REPAIRLOCFLAG" BIGINT NOT NULL , 
		  "INTSHIFT" VARGRAPHIC(10 CODEUNITS16) , 
		  "PCPCHANGEBY" VARGRAPHIC(36 CODEUNITS16) , 
		  "PCPCHANGEDATE" TIMESTAMP , 
		  "PCPHYS" BIGINT , 
		  "PCACTHRS" BIGINT , 
		  "PCTASKCOMP" BIGINT , 
		  "OOG_DEGRADED" BIGINT , 
		  "OOG_ROTARY" DECIMAL(15,2) , 
		  "OOG_WATERDEPTH" DECIMAL(15,2) , 
		  "OOG_INTERVENTIONTYPE_DESC" VARGRAPHIC(240 CODEUNITS16) , 
		  "OOG_TYPE" VARGRAPHIC(19 CODEUNITS16) , 
		  "OOG_INIT_DAYQUANTITY" BIGINT , 
		  "OOG_INIT_STARTDATE" TIMESTAMP , 
		  "OOG_EMERGENCIAL" BIGINT NOT NULL , 
		  "GEOMETRY" BLOB(1073741824) LOGGED NOT COMPACT , 
		  "ANYWHEREREFID" BIGINT , 
		  "SPLANREVIEWDATE" TIMESTAMP , 
		  "UNITSOFWORK" VARGRAPHIC(30 CODEUNITS16) , 
		  "DJPAPPLIED" VARGRAPHIC(6 CODEUNITS16) NOT NULL , 
		  "DJPERROR" VARGRAPHIC(480 CODEUNITS16) , 
		  "PLUSGPERMITWORKNUM" VARGRAPHIC(10 CODEUNITS16) , 
		  "PLUSGISOLATIONNUM" VARGRAPHIC(10 CODEUNITS16) , 
		  "PLUSGFAILIMPACTONFUNCTION" VARGRAPHIC(42 CODEUNITS16) , 
		  "PLUSGOPERATIONALPHASEATFAILURE" VARGRAPHIC(48 CODEUNITS16) , 
		  "PLUSGOPERCONDATFAILURE" VARGRAPHIC(42 CODEUNITS16) , 
		  "PLUSGCONSQNUM" VARGRAPHIC(12 CODEUNITS16) , 
		  "PLUSGORIGRECEVTID" BIGINT , 
		  "PLUSGCONSQID" BIGINT , 
		  "PLUSGSECEGRP" VARGRAPHIC(30 CODEUNITS16) , 
		  "PLUSGDEGFACT" VARGRAPHIC(24 CODEUNITS16) , 
		  "MILESTONE" BIGINT NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL )   
		 DATA CAPTURE CHANGES  
		 IN "MAXDATA" INDEX IN "MAXINDEX"  
		 ORGANIZE BY ROW;

CREATE INDEX "MAXIMO  "."IDX_WORKORDER_PERF" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC,
		 "HISTORYFLAG" ASC,
		 "ISTASK" ASC,
		 "STATUS" ASC,
		 "TARGCOMPDATE" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."IDX_WO_TARGCOMPDATE" ON "MAXIMO  "."WORKORDER" 
		("TARGCOMPDATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_N5" ON "MAXIMO  "."WORKORDER" 
		("STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_N6" ON "MAXIMO  "."WORKORDER" 
		("HISTORYFLAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_N7" ON "MAXIMO  "."WORKORDER" 
		("ISTASK" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE UNIQUE INDEX "MAXIMO  "."WORKORDER_NDX1" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX10" ON "MAXIMO  "."WORKORDER" 
		("PARENT" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX15" ON "MAXIMO  "."WORKORDER" 
		("SUPERVISOR" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX17" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX18" ON "MAXIMO  "."WORKORDER" 
		("ORIGRECORDID" ASC,
		 "ORIGRECORDCLASS" ASC,
		 "WOCLASS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX19" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "PARENT" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX2" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX20" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "HISTORYFLAG" ASC,
		 "WONUM" ASC,
		 "ISTASK" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX21" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC,
		 "ISTASK" ASC,
		 "SITEID" ASC,
		 "HISTORYFLAG" ASC,
		 "WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX22" ON "MAXIMO  "."WORKORDER" 
		("REPORTEDBY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX23" ON "MAXIMO  "."WORKORDER" 
		("ONBEHALFOF" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX24" ON "MAXIMO  "."WORKORDER" 
		("HISTORYFLAG" ASC,
		 "ISTASK" ASC,
		 "WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX25" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC,
		 "WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX26" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC,
		 "ORIGRECORDID" ASC,
		 "ORIGRECORDCLASS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX27" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "WOCLASS" ASC,
		 "HISTORYFLAG" ASC,
		 "ISTASK" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX28" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX29" ON "MAXIMO  "."WORKORDER" 
		("PMNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX3" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "HISTORYFLAG" ASC,
		 "WOCLASS" ASC,
		 "ISTASK" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE UNIQUE INDEX "MAXIMO  "."WORKORDER_NDX30" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX31" ON "MAXIMO  "."WORKORDER" 
		("PMNUM" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX32" ON "MAXIMO  "."WORKORDER" 
		("WOGROUP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX33" ON "MAXIMO  "."WORKORDER" 
		("OWNER" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX34" ON "MAXIMO  "."WORKORDER" 
		("REPFACSITEID" ASC,
		 "REPAIRFACILITY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX35" ON "MAXIMO  "."WORKORDER" 
		("WOGROUP" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX37" ON "MAXIMO  "."WORKORDER" 
		("PLUSCPHYLOC" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX38" ON "MAXIMO  "."WORKORDER" 
		("PLUSGRISKASSESSID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX39" ON "MAXIMO  "."WORKORDER" 
		("PLUSGPROCEDUREID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX40" ON "MAXIMO  "."WORKORDER" 
		("PLUSGSHIFTLOGID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX41" ON "MAXIMO  "."WORKORDER" 
		("PLUSGCFWNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX42" ON "MAXIMO  "."WORKORDER" 
		("PLUSGRFWNUM" ASC,
		 "PLUSGFUNCTION" ASC,
		 "ORGID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX43" ON "MAXIMO  "."WORKORDER" 
		("REQASSTDWNTIME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX44" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "SITEID" ASC,
		 "ISTASK" ASC,
		 "INCTASKSINSCHED" ASC,
		 "PARENT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX45" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "INCTASKSINSCHED" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX46" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "ISTASK" ASC,
		 "WOCLASS" ASC,
		 "STATUS" ASC,
		 "HISTORYFLAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX47" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX48" ON "MAXIMO  "."WORKORDER" 
		("FINCNTRLID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX49" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "WOCLASS" ASC,
		 "TARGCOMPDATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX50" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "ISTASK" ASC,
		 "TARGSTARTDATE" ASC,
		 "ONBEHALFOF" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX51" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "WOCLASS" ASC,
		 "REPORTDATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX52" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "TARGCOMPDATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX53" ON "MAXIMO  "."WORKORDER" 
		("CINUM" ASC,
		 "WOCLASS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX54" ON "MAXIMO  "."WORKORDER" 
		("LOCATION" ASC,
		 "SITEID" ASC,
		 "TARGSTARTDATE" ASC,
		 "STATUS" ASC,
		 "WORKTYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX55" ON "MAXIMO  "."WORKORDER" 
		("PERSONGROUP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX56" ON "MAXIMO  "."WORKORDER" 
		("OWNERGROUP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX58" ON "MAXIMO  "."WORKORDER" 
		("WORKORDERID" ASC,
		 "WONUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX59" ON "MAXIMO  "."WORKORDER" 
		("STATUS" ASC,
		 "SCHEDSTART" ASC,
		 "WORKORDERID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX6" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "RESPONDBY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX60" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "SITEID" ASC,
		 "IGNORESRMAVAIL" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX61" ON "MAXIMO  "."WORKORDER" 
		("WOCLASS" ASC,
		 "HISTORYFLAG" ASC,
		 "REPAIRLOCFLAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX62" ON "MAXIMO  "."WORKORDER" 
		("WORKTYPE" ASC,
		 "WOCLASS" ASC,
		 "HISTORYFLAG" ASC,
		 "TARGCOMPDATE" ASC,
		 "TARGSTARTDATE" ASC,
		 "SCHEDFINISH" ASC,
		 "SCHEDSTART" ASC,
		 "WONUM" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX63" ON "MAXIMO  "."WORKORDER" 
		("ASSETNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX64" ON "MAXIMO  "."WORKORDER" 
		("WONUM" ASC,
		 "SITEID" ASC,
		 "HISTORYFLAG" ASC,
		 "PARENT" ASC,
		 "WORKORDERID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX65" ON "MAXIMO  "."WORKORDER" 
		("OOG_CONCDATE" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX66" ON "MAXIMO  "."WORKORDER" 
		("PLUSGPERTYPEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX67" ON "MAXIMO  "."WORKORDER" 
		("PLUSGHAZARDUID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX68" ON "MAXIMO  "."WORKORDER" 
		("PLUSGBENNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX69" ON "MAXIMO  "."WORKORDER" 
		("WOGROUP" ASC,
		 "TASKID" ASC,
		 "ORGID" ASC,
		 "HISTORYFLAG" ASC,
		 "WORKORDERID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX7" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "ASSETNUM" ASC,
		 "PROBLEMCODE" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX8" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "JPNUM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_NDX9" ON "MAXIMO  "."WORKORDER" 
		("SITEID" ASC,
		 "LOCATION" ASC,
		 "PROBLEMCODE" ASC,
		 "STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_PRIORITY" ON "MAXIMO  "."WORKORDER" 
		("WOPRIORITY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_WC_NDX01" ON "MAXIMO  "."WORKORDER" 
		("STATUS" ASC,
		 "HISTORYFLAG" ASC,
		 "ISTASK" ASC,
		 "WORKORDERID" ASC,
		 "SUPERVISOR" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_WC_NDX02" ON "MAXIMO  "."WORKORDER" 
		("STATUS" ASC,
		 "WOCLASS" ASC,
		 "ISTASK" ASC,
		 "WORKORDERID" ASC,
		 "SITEID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "MAXIMO  "."WORKORDER_WC_NDX03" ON "MAXIMO  "."WORKORDER" 
		("STATUS" ASC,
		 "HISTORYFLAG" ASC,
		 "ISTASK" ASC,
		 "WORKORDERID" ASC,
		 "WORKTYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "MAXIMO  "."WORKORDER" 
	ADD PRIMARY KEY
		("WORKORDERID")
	ENFORCED;

CREATE TRIGGER WORKORDER_T NO CASCADE BEFORE INSERT ON WORKORDER REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

CREATE TRIGGER WORKORDER_U NO CASCADE BEFORE UPDATE ON WORKORDER REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL SET N.ROWSTAMP = NEXTVAL FOR MAXSEQ;

GRANT ALTER ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT DELETE ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT INDEX ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT INSERT ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT SELECT ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT UPDATE ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT REFERENCES ON TABLE "MAXIMO  "."WORKORDER" TO USER "CDCADMIN";

GRANT CONTROL ON TABLE "MAXIMO  "."WORKORDER" TO USER "MAXIMO  ";

GRANT SELECT ON TABLE "MAXIMO  "."WORKORDER" TO USER "MAXORA  ";

GRANT ALTER ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT DELETE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT INDEX ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT INSERT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT SELECT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT UPDATE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT REFERENCES ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_DATALAKE";

GRANT ALTER ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT DELETE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT INDEX ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT INSERT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT SELECT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT UPDATE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT REFERENCES ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_LIVE";

GRANT ALTER ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT DELETE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT INDEX ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT INSERT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT SELECT ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT UPDATE ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT REFERENCES ON TABLE "MAXIMO  "."WORKORDER" TO USER "RAC_SMART";

GRANT CONTROL ON INDEX "MAXIMO  "."IDX_WORKORDER_PERF" TO USER "MAXIMO  ";

GRANT CONTROL ON INDEX "MAXIMO  "."IDX_WO_TARGCOMPDATE" TO USER "MAXIMO  ";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_N5" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_N6" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_N7" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX1" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX10" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX15" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX17" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX18" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX19" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX2" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX20" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX21" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX22" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX23" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX24" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX25" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX26" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX27" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX28" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX29" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX3" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX30" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX31" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX32" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX33" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX34" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX35" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX37" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX38" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX39" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX40" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX41" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX42" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX43" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX44" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX45" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX46" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX47" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX48" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX49" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX50" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX51" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX52" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX53" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX54" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX55" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX56" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX58" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX59" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX6" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX60" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX61" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX62" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX63" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX64" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX65" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX66" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX67" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX68" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX69" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX7" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX8" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_NDX9" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_PRIORITY" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_WC_NDX01" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_WC_NDX02" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "MAXIMO  "."WORKORDER_WC_NDX03" TO USER "DB2INST1";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL251206163908870" TO USER "MAXIMO  ";